### ISSUE TITLE
Version upgrade @sentry/node

### ISSUE THREAD

**Issue by LerenDevTeam** [reg2005/adonis5-sentry#10]
In project Dashboard, Sentry is asking me to upgrade from 6.x to 7.x:

https://github.com/getsentry/sentry-javascript/blob/7.0.0/MIGRATION.md#upgrading-from-6x-to-7x

Package version
"adonis5-sentry": "^3.1.0"

**Comment by laxadev** [comment]
@reg2005 Can you please upgrade it?

**Comment by thalesog** [comment]
Just sent a PR with the upgraded version. (#11)

@reg2005 can you merge it for us?

**Comment by thalesog** [comment]
@reg2005 @VladyslavParashchenko bump!

**Comment by tsatsujnr139** [comment]
@reg2005 bump!

**Comment by thalesog** [comment]
Guys, as the maintainer of this repository isn't accepting our PR, we upgraded using the yarn `resolutions` method.

Insert the following parameters on `package.json` file:
```json
  "resolutions": {
    "@sentry/node": "7.34.0"
  }
```

**Comment by reg2005** [comment]
Less than a year later, we did it)
