### ISSUE TITLE
SentryProvider.register

### ISSUE THREAD

**Issue by 3dkEd** [reg2005/adonis5-sentry#5]
Error Found upon serve

TypeError: this.container.singleton is not a function

1 SentryProvider.register

## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

- Lots of raised issues are directly not bugs but instead are design decisions taken by us.
- Make use of our [forum](https://forum.adonisjs.com/), or [discord server](https://discord.me/adonisjs), if you are not sure that you are reporting a bug.
- Ensure the issue isn't already reported.
- Ensure you are reporting the bug in the correct repo.

*Delete the above section and the instructions in the sections below before submitting*

## Package version
1.1.0

## Node.js and npm version
v16.2.0

## Sample Code (to reproduce the issue)
Error found after i install the package

![image](https://user-images.githubusercontent.com/80746401/120404919-027b6600-c37a-11eb-8923-7cdf0bd4ab84.png)

**Comment by 3dkEd** [comment]
it works when i add **.container** in constructor

node_modules/adonis5-sentry/build/providers/SentryProvider.js

![image](https://user-images.githubusercontent.com/80746401/120404723-926ce000-c379-11eb-82fa-9bf94ca9e7ef.png)

**Comment by ms1sistemas** [comment]
I have the same problem

**Comment by VladyslavP98** [comment]
Please install via github branch ```npm i git://github.com:reg2005/adonis5-sentry.git#update```
My colleague @reg2005  will publish update to npm soon

**Comment by reg2005** [comment]
#4 merged, npm package was publish

**Comment by ms1sistemas** [comment]
Thank you so much
